version: "3.9"

services:
    zookeeper:
        image: arm64v8/zookeeper:3.7
        platform: linux/arm64
        ports:
            - "2181:2181"

    kafka:
        image: arm64v8/kafka:2.8.1
        platform: linux/arm64
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    schema-registry:
        image: vectorizedio/schema-registry:latest
        platform: linux/arm64
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_KAFKA_BROKERS: "kafka:9092"

    postgres:
        image: arm64v8/postgres:15
        platform: linux/arm64
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=supabase
            - POSTGRES_USER=supabase
            - POSTGRES_PASSWORD=supabase

    elasticsearch:
        image: arm64v8/elasticsearch:8.5.1
        platform: linux/arm64
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
